services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend
      - "5001:5000"  # Backend API (changed from 5000:5000)
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - PROXMOX_CONTAINER=true  # Added environment variable
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server/node_modules
    networks:
      - default
      - supabase_default

networks:
  supabase_default:
    external: true
