arch: amd64
ostype: ubuntu
memory: 2048
swap: 512
cores: 2
hostname: project-management-tool
net0: name=eth0,bridge=vmbr0,ip=dhcp
rootfs: local-lvm:vm-100-disk-0,size=8G
description: "Container for Project Management Tool"
